name: Simplified Validate Commits

on:
  push:
    branches:
      - master

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display Git Info
        run: |
          echo "GITHUB_SHA: $GITHUB_SHA"
          git log --oneline -n 5
          git diff --name-only $GITHUB_SHA^..$GITHUB_SHA
        shell: bash
