name: Validate Commits

on:
  push:
    branches:
      - master

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate Commits
        run: |
          git fetch origin master
          range="${{ github.event.before }}..${{ github.sha }}"
          git log --pretty=oneline $range
          git diff --name-only $range
        shell: bash
