name: Check Commit Message

on: [push, pull_request]

jobs:
  check-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Check commit message
      run: npm run check-commit < "$(git log -1 --pretty=%B)"
