name: Commitlint Check

on:
  push:
    branches:
      - master # 更改为你的默认分支

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install Dependencies
      run: |
        npm install -g @commitlint/cli @commitlint/config-conventional
        npm install

    - name: Get Last Commit Message
      id: last_commit
      run: echo "::set-output name=commit_message::$(git log -1 --pretty=%B)"

    - name: Create Temporary File
      id: temp_file
      run: echo "${{ steps.last_commit.outputs.commit_message }}" > temp_commit_message.txt

    - name: Run Commitlint
      run: npx commitlint --edit --env EDITOR="cat ${{ steps.temp_file.outputs.temp_file }}"
