name: Validate Commits

on:
  push:
    branches:
      - master

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate Commits
        uses: joberstein/actions-commitlint-validation@v1-dist
        with:
          extra_config: "@joberstein12/commitlint-config"
          commit_range: "-- ${{ github.sha }}"
